# Generated by Django 3.2.5 on 2021-11-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivEloWins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilization', models.IntegerField()),
                ('map_id', models.IntegerField()),
                ('ladder_id', models.IntegerField()),
                ('patch_number', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('victory_count', models.IntegerField()),
                ('loss_count', models.IntegerField()),
            ],
            options={
                'db_table': 'civ_elo_wins',
            },
        ),
        migrations.CreateModel(
            name='Ladders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ladders',
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'maps',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_elo', models.IntegerField()),
                ('map_id', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('patch_id', models.FloatField()),
                ('ladder_id', models.IntegerField(blank=True, null=True)),
                ('patch_number', models.IntegerField()),
                ('player1_opening_flag0', models.BooleanField()),
                ('player1_opening_flag1', models.BooleanField()),
                ('player1_opening_flag2', models.BooleanField()),
                ('player1_opening_flag3', models.BooleanField()),
                ('player1_opening_flag4', models.BooleanField()),
                ('player1_opening_flag5', models.BooleanField()),
                ('player1_opening_flag6', models.BooleanField()),
                ('player1_opening_flag7', models.BooleanField()),
                ('player1_opening_flag8', models.BooleanField()),
                ('player1_opening_flag9', models.BooleanField()),
                ('player1_opening_flag10', models.BooleanField()),
                ('player1_opening_flag11', models.BooleanField()),
                ('player1_opening_flag12', models.BooleanField()),
                ('player1_opening_flag13', models.BooleanField()),
                ('player1_opening_flag14', models.BooleanField()),
                ('player1_opening_flag15', models.BooleanField()),
                ('player1_opening_flag16', models.BooleanField()),
                ('player1_opening_flag17', models.BooleanField()),
                ('player1_opening_flag18', models.BooleanField()),
                ('player1_opening_flag19', models.BooleanField()),
                ('player1_opening_flag20', models.BooleanField()),
                ('player1_opening_flag21', models.BooleanField()),
                ('player1_opening_flag22', models.BooleanField()),
                ('player1_opening_flag23', models.BooleanField()),
                ('player1_opening_flag24', models.BooleanField()),
                ('player1_opening_flag25', models.BooleanField()),
                ('player1_opening_flag26', models.BooleanField()),
                ('player1_opening_flag27', models.BooleanField()),
                ('player1_opening_flag28', models.BooleanField()),
                ('player1_opening_flag29', models.BooleanField()),
                ('player1_opening_flag30', models.BooleanField()),
                ('player1_opening_flag31', models.BooleanField()),
                ('player1_civilization', models.IntegerField()),
                ('player1_victory', models.IntegerField()),
                ('player1_parser_version', models.IntegerField()),
                ('player2_opening_flag0', models.BooleanField()),
                ('player2_opening_flag1', models.BooleanField()),
                ('player2_opening_flag2', models.BooleanField()),
                ('player2_opening_flag3', models.BooleanField()),
                ('player2_opening_flag4', models.BooleanField()),
                ('player2_opening_flag5', models.BooleanField()),
                ('player2_opening_flag6', models.BooleanField()),
                ('player2_opening_flag7', models.BooleanField()),
                ('player2_opening_flag8', models.BooleanField()),
                ('player2_opening_flag9', models.BooleanField()),
                ('player2_opening_flag10', models.BooleanField()),
                ('player2_opening_flag11', models.BooleanField()),
                ('player2_opening_flag12', models.BooleanField()),
                ('player2_opening_flag13', models.BooleanField()),
                ('player2_opening_flag14', models.BooleanField()),
                ('player2_opening_flag15', models.BooleanField()),
                ('player2_opening_flag16', models.BooleanField()),
                ('player2_opening_flag17', models.BooleanField()),
                ('player2_opening_flag18', models.BooleanField()),
                ('player2_opening_flag19', models.BooleanField()),
                ('player2_opening_flag20', models.BooleanField()),
                ('player2_opening_flag21', models.BooleanField()),
                ('player2_opening_flag22', models.BooleanField()),
                ('player2_opening_flag23', models.BooleanField()),
                ('player2_opening_flag24', models.BooleanField()),
                ('player2_opening_flag25', models.BooleanField()),
                ('player2_opening_flag26', models.BooleanField()),
                ('player2_opening_flag27', models.BooleanField()),
                ('player2_opening_flag28', models.BooleanField()),
                ('player2_opening_flag29', models.BooleanField()),
                ('player2_opening_flag30', models.BooleanField()),
                ('player2_opening_flag31', models.BooleanField()),
                ('player2_civilization', models.IntegerField()),
                ('player2_victory', models.IntegerField()),
                ('player2_parser_version', models.IntegerField()),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='OpeningEloWins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening1_id', models.IntegerField()),
                ('opening2_id', models.IntegerField()),
                ('map_id', models.IntegerField()),
                ('ladder_id', models.IntegerField()),
                ('patch_number', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('opening1_victory_count', models.IntegerField()),
                ('opening1_loss_count', models.IntegerField()),
                ('opening2_victory_count', models.IntegerField()),
                ('opening2_loss_count', models.IntegerField()),
            ],
            options={
                'db_table': 'opening_elo_wins',
            },
        ),
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'openings',
            },
        ),
        migrations.CreateModel(
            name='Patches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'patches',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'techs',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opening_stats.matches')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opening_stats.players')),
            ],
            options={
                'db_table': 'match_player_actions',
            },
        ),
        migrations.AddField(
            model_name='matches',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_player1', to='opening_stats.players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_player2', to='opening_stats.players'),
        ),
    ]
