# Generated by Django 3.2.5 on 2021-11-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningEloTechs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_id', models.IntegerField()),
                ('tech_id', models.IntegerField()),
                ('map_id', models.IntegerField()),
                ('ladder_id', models.IntegerField()),
                ('patch_number', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('time_bucket', models.IntegerField()),
                ('average_time', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'opening_elo_techs',
            },
        ),
    ]
