# Generated by Django 3.2.5 on 2021-11-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0003_alter_matchplayeractions_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingelotechs',
            name='time_bucket',
        ),
    ]
