# Generated by Django 3.2.5 on 2021-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0004_remove_openingelotechs_time_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingelotechs',
            name='average_time',
            field=models.FloatField(),
        ),
    ]
