# Generated by Django 3.2.5 on 2021-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0005_alter_openingelotechs_average_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='techs',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
