# Generated by Django 3.2.5 on 2021-11-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0006_techs_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='civelowins',
            unique_together={('civilization', 'map_id', 'ladder_id', 'patch_number', 'elo')},
        ),
        migrations.AlterUniqueTogether(
            name='openingelotechs',
            unique_together={('opening_id', 'tech_id', 'map_id', 'ladder_id', 'patch_number', 'elo')},
        ),
        migrations.AlterUniqueTogether(
            name='openingelowins',
            unique_together={('opening1_id', 'opening2_id', 'map_id', 'ladder_id', 'patch_number', 'elo')},
        ),
    ]
