# Generated by Django 3.2.5 on 2021-11-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0007_auto_20211129_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civelowins',
            name='loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='civelowins',
            name='victory_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openingelotechs',
            name='average_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='openingelotechs',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openingelowins',
            name='opening1_loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openingelowins',
            name='opening1_victory_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openingelowins',
            name='opening2_loss_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openingelowins',
            name='opening2_victory_count',
            field=models.IntegerField(default=0),
        ),
    ]
