# Generated by Django 3.2.10 on 2022-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0011_advancedqueryresults_alter_advancedqueryqueue_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='patches',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
