# Generated by Django 3.2.13 on 2022-05-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening_stats', '0012_patches_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchplayeractions',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchplayeractions',
            name='player',
        ),
        migrations.DeleteModel(
            name='OpeningEloTechs',
        ),
        migrations.DeleteModel(
            name='Techs',
        ),
        migrations.DeleteModel(
            name='MatchPlayerActions',
        ),
    ]
